#!/usr/bin/env bash
set -e

NAME="$1"
ACTION="$2"

BASE_DIR="$HOME"
GITHUB_DIR="$HOME/personal/github"
CONTRIB_DIR="$HOME/work/contrib"

IMAGE_PREFIX="dev"
CONTAINER="$IMAGE_PREFIX-$NAME"
IMAGE="$IMAGE_PREFIX-$NAME:latest"

COMMON_ARGS=(
  --userns=keep-id
  --security-opt=label=disable
  --device=/dev/dri
  -v "$GITHUB_DIR:/workspace/github"
  -v "$CONTRIB_DIR:/workspace/contrib"
  -v "$HOME/.cache/dev/pip:/home/dev/.cache/pip"
  -v "$HOME/.cache/dev/venv:/home/dev/.venv"
)

usage() {
  echo "Usage:"
  echo "  dev up <devenv|pytorch|llvm>"
  echo "  dev shell <devenv|pytorch|llvm>"
  echo "  dev stop <devenv|pytorch|llvm>"
  exit 1
}

[ -z "$NAME" ] && usage
[ -z "$ACTION" ] && usage

case "$ACTION" in
  up)
    podman container exists "$CONTAINER" && {
      echo "[+] Container already exists: $CONTAINER"
      exit 0
    }

    echo "[+] Starting container $CONTAINER"
    podman run -d \
      --name "$CONTAINER" \
      "${COMMON_ARGS[@]}" \
      "$IMAGE" sleep infinity
    ;;

  shell)
    podman exec -it "$CONTAINER" bash
    ;;

  stop)
    podman stop "$CONTAINER"
    ;;

  *)
    usage
    ;;
esac

