#!/usr/bin/env bash
set -euo pipefail # Added 'u' to error on unset vars and 'o pipefail' for better error catching

ACTION="$1" # Action to perform
NAME="$2" # Name of the container

BASE_PERSONAL_DIR="$HOME/personal" # Do not mount this directory
BASE_WORK_DIR="$HOME/work" # Do not mount this directory
GITHUB_DIR="$BASE_PERSONAL_DIR/github"
CONTRIB_DIR="$BASE_WORK_DIR/contrib"
PROJECT_DIR="$BASE_WORK_DIR/project"
CONFIG_DIR="$HOME/.config"

IMAGE_PREFIX="dev"
CONTAINER="$IMAGE_PREFIX-$NAME"
IMAGE="localhost/$IMAGE_PREFIX-$NAME:latest"

COMMON_ARGS=(
  --userns=keep-id:uid=1000,gid=1000
  --security-opt=label=disable
  --device=/dev/snd 
  --device=/dev/kfd 
  --device=/dev/dri
  -v "$GITHUB_DIR:/home/pydevc/personal/github:z"
  -v "$CONTRIB_DIR:/home/pydevc/work/contrib:z"
  -v "$PROJECT_DIR:/home/pydevc/work/project:z"
  -v "$CONFIG_DIR:/home/pydevc/.config:z"
)

usage() {
  echo "Usage:"
  echo "  dev up <devenv|pytorch|llvm>"
  echo "  dev shell <devenv|pytorch|llvm>"
  echo "  dev stop <devenv|pytorch|llvm>"
  exit 1
}

[ -z "$NAME" ] && usage
[ -z "$ACTION" ] && usage

case "$ACTION" in
  up)
    podman container exists "$CONTAINER" && {
      echo "[+] Container already exists: $CONTAINER"
      podman start $CONTAINER
      echo "[+] Container Started: $CONTAINER"
      exit 0
    }

    echo "[+] Starting container $CONTAINER"
    podman run -d \
      --name "$CONTAINER" \
      "${COMMON_ARGS[@]}" \
      "$IMAGE" sleep infinity
    ;;

  shell)
    if [[ "$(podman inspect -f '{{.State.Running}}' "$CONTAINER" 2>/dev/null)" == "true" ]]; then
        podman exec -it -u pydevc "$CONTAINER" bash
    else
        echo "[!] Container $CONTAINER is not running. Try 'up' first."
    fi
    ;;

  stop)
    podman stop "$CONTAINER"
    ;;

  *)
    usage
    ;;
esac

