FROM rocm/pytorch:rocm6.0_ubuntu22.04_py3.10_pytorch_release_2.1.0

RUN apt update && apt install -y \
    git zsh tmux \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m dev
USER dev
WORKDIR /workspace

ENV PIP_CACHE_DIR=/home/dev/.cache/pip
ENV VIRTUAL_ENV=/home/dev/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

CMD ["bash"]

